#!/bin/bash

#    DIY webcam-driven home surveillance system
#    Copyright (C) 2015 Gabriele Musco
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

maxdiff=5 #maximum percentage of change allowed between pictures to confirm there has been no movement or people passing by
mtimer=10
fswebcam -r 640x480 --jpeg 85 -D 1 1.jpg #take the first control picture with fswebcam
while [ true ]
do
	sleep $mtimer #time interval between security checks, in seconds
	fswebcam -r 640x480 --jpeg 85 -D 1 2.jpg #take a comparison picture with fswebcam
	res=$(./imagecompare 2.jpg 1.jpg) #save the return value of imagecompare to make a comparison
	if [ "$maxdiff" -le "$res" ] #condition to trigger the security measures
	then
		FILENAME=$(date +%Y-%m-%d_%H.%M.%S).jpg
		mv 2.jpg $FILENAME
		./dropbox-uploader/dropbox_uploader.sh upload $FILENAME ./
		mtimer=3
	else
		mv 2.jpg 1.jpg #if nothing particular happened according to the algorithm, replace the control picture with the second photo to minimize difference in long time
		mtimer=10
	fi
done

